
     # project:  project1

trigger:
- master

stages:
 - stage: ProduceArtifact
   jobs:
     - deployment: deploymentJob10
       environment: envionment10
       pool: Default
       strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Hello, world! 
                displayName: 'Run a one-line script'
     - deployment: deploymentJob11
       environment: envionment11
       pool: Default
       strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Hello, world! 
                displayName: 'Run a one-line script'
              # - task: PublishBuildArtifacts@1
              #   inputs:
              #     PathtoPublish: 'artifact3'
              #     ArtifactName: 'A3_Project2'
              #     publishLocation: 'Container'
    #  - job: J4
    #    pool: 
    #     name: Default
    #    steps:
    #      - download: P1
    #        artifact: A1.1
    #      - task: PublishBuildArtifacts@1
    #        inputs:
    #         PathtoPublish: 'artifact3'
    #         ArtifactName: 'A3_Project2'
    #         publishLocation: 'Container'
        #  -  powershell: |
        #     ls $(Build.ArtifactStagingDirectory)/
